# Generated by Django 5.1 on 2024-09-02 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'custom_service_table_name',
            },
        ),
        migrations.CreateModel(
            name='LocalArea',
            fields=[
                ('local_area_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('local_area_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Exactly 10 digits allowed.", regex='^\\d{10}$')])),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afapp.district')),
                ('local_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afapp.localarea')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afapp.service')),
            ],
        ),
    ]
