# Generated by Django 5.1 on 2024-09-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
    ]
